language: node_js
cache:
  directories:
  - node_modules
script:
- npm run coveralls
deploy:
  provider: npm
  email: sergey.v.klimov@gmail.com
  api_key:
    secure: Yyw4Bm1EmChUX3FRUCmalAlnNt4S9HUGryApV4KMpdftDBWjavYpv30DTrDybWwdBDtcq8XuUeQkAlYwCWO+R72DZTS7stViQ1MPBwM4dyihrGEsY91+5lFwieVP+DhN5K3+ETEp/FscyGCq1wFwukb8lkMHbaERgTnZuX0E0wnxE+DdfCbEZttNwrCWOjXDK7/2jyQPmRzrKCh3RF48GQBmQsTn/4MWmOfcYgfNmCR30iA+XwuDcNEjao3v734b8tKGnf28neWHTsG/xa5LubvfaQxMdf4nHO8MGs8DkKLc6wP34TTmljiRqkstIxbQ11Ff+aLa/Z5F+zHvsR8ZTwuoCnvE9TGT7D2xMUxLaMw+GSGELo+etVmfac1yTyExKI5Ova3bzDQ4b+Z/a1xVf3EKNX9n2soDzeDlOBDVNsoHGiZj2tPQ2/U1neblkIhPje5g04Wg48HWF3g49+MvzNA+Wfs8brDAIy+y4b4e1jNWwqWZ8WfNGE5oq9+9CWCSIlyxi16PMWYHxHhGhenshdgEc/qm43ZAjJJScH2OAoVANB5HJyavn6qZtVju0XK5/VElhgeF3vZqjSSQ5O/jAPOqZV3OjCRsLZqW7Zez0V90FaJ2nQiibyCb9KGFJd9E9E+FRKobh8z9LqFbrvywmcMhN8O2dWgN3do5C14DoJo=
  on:
    tags: true
    repo: darvin/enwiktionary-analyzer
